<?xml version="1.0"?>
<package format="3">

    <name>eval_cie</name>
    <version>0.0.1</version>

    <description>
        Callback Isolated Executor experiment container
    </description>

    <maintainer email="you@example.com">
        you
    </maintainer>

    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>std_msgs</depend>
    <depend>callback_isolated_executor</depend>
    <depend>lttng-ust</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>

</package>